version: '3'

services:
  spring-boot:
    restart: 'on-failure'
    build: .
    depends_on:
      - mysql
      - redis
    ports:
      - '8000:8000'
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - auth-mysql-vol:/var/lib/mysql
    env_file:
      - .env
    restart: 'on-failure'
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - auth-redis-vol:/var/lib/redis
    restart: 'on-failure'

volumes:
  auth-mysql-vol:
  auth-redis-vol: