version: '3'

services:
  mysql:
    image: mysql:latest
    volumes:
      - auth-mysql-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2023
      MYSQL_DATABASE: auth
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_user_pass
    restart: always
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - auth-redis-vol:/var/lib/redis
    restart: always

volumes:
  auth-mysql-vol:
  auth-redis-vol: