drop table if exists salt CASCADE;
create table salt
(
    id bigint generated by default as identity,
    salt varchar(128) not null,
    primary key(id)
);

drop table if exists member CASCADE;
create table member
(
    id  bigint generated by default as identity,
    username varchar(20) not null unique,
    password varchar(128) not null,
    name varchar(20) not null,
    email varchar(128) not null unique,
    role varchar(128) not null,
    create_At datetime,
    update_At datetime,
    salt_id int,
    primary key (id),
    foreign key(salt_id) references salt(id)
);